// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2SsMhZLx4AYMLQPwW2y0LA1b5Ggx8FqY',
    appId: '1:202964450762:web:d556ad8e90b986f0632333',
    messagingSenderId: '202964450762',
    projectId: 'final-project-a53c5',
    authDomain: 'final-project-a53c5.firebaseapp.com',
    storageBucket: 'final-project-a53c5.appspot.com',
    measurementId: 'G-1CCTWGNKRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrF6WvMgiJlSAZFmBiG1jKpNcYx4NMHBc',
    appId: '1:202964450762:android:251576826e2831b2632333',
    messagingSenderId: '202964450762',
    projectId: 'final-project-a53c5',
    storageBucket: 'final-project-a53c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlQb8pWVbLJp04ZG0bsKPbMJsgZno1G0w',
    appId: '1:202964450762:ios:f7995dd73d1c75c3632333',
    messagingSenderId: '202964450762',
    projectId: 'final-project-a53c5',
    storageBucket: 'final-project-a53c5.appspot.com',
    iosClientId: '202964450762-tdj4a347aql1pl2qb7kg920gjuutt4q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
